spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mediclam_db
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    # properties:
    #   hibernate:
    #     format_sql: true

  servlet:
    multipart:
      enabled: true
      max-file-size: 1MB
      max-request-size: 2MB

  web:
    resources:
      static-locations: file:uploads/

server:
 
  #port: 2028
