spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mediclam_db
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  servlet:
    multipart:
      max-file-size: 5MB

  # 🔥 ADD THIS BLOCK
  mail:
    host: smtp.gmail.com
    port: 587
    username: kushal.bhadra.project@gmail.com
    password: 427883
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true